2025-04-29 17:59:33,436 INFO    MainThread:33044 [wandb_setup.py:_flush():68] Current SDK version is 0.19.5
2025-04-29 17:59:33,437 INFO    MainThread:33044 [wandb_setup.py:_flush():68] Configure stats pid to 33044
2025-04-29 17:59:33,437 INFO    MainThread:33044 [wandb_setup.py:_flush():68] Loading settings from /home01/x3100a06/.config/wandb/settings
2025-04-29 17:59:33,437 INFO    MainThread:33044 [wandb_setup.py:_flush():68] Loading settings from /scratch/x3100a06/MLP_Paper/CIGNN/wandb/settings
2025-04-29 17:59:33,437 INFO    MainThread:33044 [wandb_setup.py:_flush():68] Loading settings from environment variables
2025-04-29 17:59:33,437 INFO    MainThread:33044 [wandb_init.py:setup_run_log_directory():637] Logging user logs to example-1/wandb_logs/wandb/run-20250429_175933-5huhuwv1/logs/debug.log
2025-04-29 17:59:33,437 INFO    MainThread:33044 [wandb_init.py:setup_run_log_directory():638] Logging internal logs to example-1/wandb_logs/wandb/run-20250429_175933-5huhuwv1/logs/debug-internal.log
2025-04-29 17:59:33,437 INFO    MainThread:33044 [wandb_init.py:init():756] calling init triggers
2025-04-29 17:59:33,437 INFO    MainThread:33044 [wandb_init.py:init():761] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-04-29 17:59:33,438 INFO    MainThread:33044 [wandb_init.py:init():789] starting backend
2025-04-29 17:59:33,871 INFO    MainThread:33044 [wandb_init.py:init():793] sending inform_init request
2025-04-29 17:59:33,903 INFO    MainThread:33044 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-04-29 17:59:33,905 INFO    MainThread:33044 [wandb_init.py:init():808] backend started and connected
2025-04-29 17:59:33,906 INFO    MainThread:33044 [wandb_init.py:init():901] updated telemetry
2025-04-29 17:59:34,006 INFO    MainThread:33044 [wandb_init.py:init():926] communicating run to backend with 90.0 second timeout
2025-04-29 18:01:04,041 ERROR   MainThread:33044 [wandb_init.py:init():1471] error in wandb.init()
Traceback (most recent call last):
  File "/home01/x3100a06/.local/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1461, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home01/x3100a06/.local/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 950, in init
    raise CommError(
wandb.errors.errors.CommError: Run initialization has timed out after 90.0 sec. Please try increasing the timeout with the `init_timeout` setting: `wandb.init(settings=wandb.Settings(init_timeout=120))`.
2025-04-29 18:01:04,135 WARNING MsgRouterThr:33044 [router.py:message_loop():75] message_loop has been closed
